#!/bin/bash

# DITTO Entity Matching Pipeline - Example Docker Commands
# This file contains example commands for common use cases

echo "=== DITTO Docker Examples ==="
echo ""

echo "1. Basic CPU-only test with 100 records:"
echo "docker run --rm -it \\"
echo "  -v \$PWD/docker_ditto_runner.py:/app/docker_ditto_runner.py \\"
echo "  -v \$PWD/checkpoints:/checkpoints \\"
echo "  -v \$PWD/output:/app/output \\"
echo "  --memory=8g --cpus=2 -w /app \\"
echo "  172.17.232.16:9001/ditto-notebook:2.0 \\"
echo "  python /app/docker_ditto_runner.py --no-gpu --sample-limit 100 --output-file /app/output/test_results.json"
echo ""

echo "2. GPU-enabled run with 1000 records:"
echo "docker run --rm -it \\"
echo "  --gpus all \\"
echo "  -v \$PWD/docker_ditto_runner.py:/app/docker_ditto_runner.py \\"
echo "  -v \$PWD/checkpoints:/checkpoints \\"
echo "  -v \$PWD/output:/app/output \\"
echo "  --memory=16g --cpus=4 \\"
echo "  -e CUDA_VISIBLE_DEVICES=0 \\"
echo "  -e CUDA_DEVICE_ORDER=PCI_BUS_ID \\"
echo "  -w /app \\"
echo "  172.17.232.16:9001/ditto-notebook:2.0 \\"
echo "  python /app/docker_ditto_runner.py --sample-limit 1000 --output-file /app/output/gpu_results.json"
echo ""

echo "3. Production mode with Hive output:"
echo "docker run --rm -it \\"
echo "  --gpus all \\"
echo "  -v \$PWD/docker_ditto_runner.py:/app/docker_ditto_runner.py \\"
echo "  -v \$PWD/checkpoints:/checkpoints \\"
echo "  --memory=16g --cpus=4 \\"
echo "  -e CUDA_VISIBLE_DEVICES=0 \\"
echo "  -w /app \\"
echo "  172.17.232.16:9001/ditto-notebook:2.0 \\"
echo "  python /app/docker_ditto_runner.py --matching-mode production --save-to-hive"
echo ""

echo "4. Custom Hive connection:"
echo "docker run --rm -it \\"
echo "  -v \$PWD/docker_ditto_runner.py:/app/docker_ditto_runner.py \\"
echo "  -v \$PWD/checkpoints:/checkpoints \\"
echo "  -v \$PWD/output:/app/output \\"
echo "  --memory=8g --cpus=2 -w /app \\"
echo "  172.17.232.16:9001/ditto-notebook:2.0 \\"
echo "  python /app/docker_ditto_runner.py \\"
echo "    --hive-host your-hive-server.com \\"
echo "    --hive-port 10000 \\"
echo "    --hive-user your-username \\"
echo "    --hive-database your_database \\"
echo "    --input-table your_database.your_table \\"
echo "    --sample-limit 500 \\"
echo "    --output-file /app/output/custom_results.json"
echo ""

echo "5. Debug mode (interactive shell):"
echo "docker run --rm -it \\"
echo "  -v \$PWD/docker_ditto_runner.py:/app/docker_ditto_runner.py \\"
echo "  -v \$PWD/checkpoints:/checkpoints \\"
echo "  -v \$PWD/output:/app/output \\"
echo "  --memory=8g --cpus=2 -w /app \\"
echo "  172.17.232.16:9001/ditto-notebook:2.0 \\"
echo "  /bin/bash"
echo ""

echo "Using the helper script (recommended):"
echo ""
echo "# Basic test"
echo "./run_ditto_docker.sh --sample-limit 100 --output-file test_results.json"
echo ""
echo "# CPU-only test"
echo "./run_ditto_docker.sh --cpu-only --sample-limit 100"
echo ""
echo "# Production run"
echo "./run_ditto_docker.sh --matching-mode production --save-to-hive"
echo ""
echo "# Custom configuration"
echo "./run_ditto_docker.sh --hive-host your-server --sample-limit 1000 --output-file results.json"
echo ""

echo "=== Matcher-Only Testing (No Hive) ==="
echo ""
echo "# Quick matcher test with sample data"
echo "./test_matcher_docker.sh --num-sample-pairs 5 --output-file quick_test.json"
echo ""
echo "# CPU-only matcher test"
echo "./test_matcher_docker.sh --cpu-only --num-sample-pairs 10"
echo ""
echo "# Test with custom data file"
echo "./test_matcher_docker.sh --input-file sample_test_data.jsonl --output-file custom_test.json"
echo ""
echo "# GPU test with more pairs"
echo "./test_matcher_docker.sh --num-sample-pairs 20 --output-file gpu_test.json"
echo ""

echo "=== Matcher-Only Testing (No Hive) ==="
echo ""
echo "# Quick matcher test with sample data"
echo "./test_matcher_docker.sh --num-sample-pairs 5 --output-file quick_test.json"
echo ""
echo "# CPU-only matcher test"
echo "./test_matcher_docker.sh --cpu-only --num-sample-pairs 10"
echo ""
echo "# Test with custom data file"
echo "./test_matcher_docker.sh --input-file sample_test_data.jsonl --output-file custom_test.json"
echo ""
echo "# GPU test with more pairs"
echo "./test_matcher_docker.sh --num-sample-pairs 20 --output-file gpu_test.json"
echo ""

echo "=== Setup Commands ==="
echo ""
echo "# Create necessary directories"
echo "mkdir -p checkpoints output"
echo ""
echo "# Copy checkpoints (adjust path as needed)"
echo "cp -r /path/to/your/checkpoints/* ./checkpoints/"
echo ""
echo "# Make scripts executable"
echo "chmod +x run_ditto_docker.sh docker_examples.sh" 